# Generated by Django 2.1.5 on 2019-01-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Author_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_bio', models.CharField(max_length=50)),
                ('author_image', models.ImageField(upload_to='authImg')),
                ('author_facebook', models.URLField(blank=True)),
                ('author_twitter', models.URLField(blank=True)),
                ('author_instagram', models.URLField(blank=True)),
                ('author_youtube', models.URLField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_message', models.TextField()),
                ('post_image', models.ImageField(upload_to='authImg')),
                ('post_tages', models.CharField(choices=[('DJANGO', 'django'), ('PYTHON', 'python'), ('WEB-DEVELOPMENT', 'web-development')], max_length=30)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Author')),
            ],
        ),
    ]
