# Generated by Django 2.1.5 on 2019-01-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_image', models.ImageField(blank=True, upload_to='OwnerImg')),
                ('see_my_portfolio', models.URLField(blank=True)),
                ('owner_twitter', models.URLField(blank=True)),
                ('owner_facebook', models.URLField(blank=True)),
                ('owner_youtube', models.URLField(blank=True)),
            ],
        ),
    ]
