# Generated by Django 2.1.5 on 2019-01-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_owner_owner_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_detail',
            name='author_image',
        ),
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default=True, upload_to='authImg'),
            preserve_default=False,
        ),
    ]
