# Generated by Django 2.1.5 on 2019-01-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20190129_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
