# Generated by Django 2.1.5 on 2019-01-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20190129_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular_post',
            name='popular_posts',
        ),
        migrations.DeleteModel(
            name='Popular_Post',
        ),
    ]
