# Generated by Django 2.1.5 on 2019-01-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20190129_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image_optional',
            field=models.ImageField(default=True, upload_to='authImg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_optional1',
            field=models.ImageField(default=True, upload_to='authImg'),
            preserve_default=False,
        ),
    ]
