# Generated by Django 2.1.5 on 2019-01-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20190129_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image_optional',
            field=models.ImageField(blank=True, upload_to='authImg'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image_optional1',
            field=models.ImageField(blank=True, upload_to='authImg'),
        ),
    ]
