# Generated by Django 2.1.5 on 2019-01-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20190129_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_message',
            new_name='post_message_first_para',
        ),
        migrations.AddField(
            model_name='post',
            name='post_message_second_para',
            field=models.TextField(blank=True, default='working'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_message_third_para',
            field=models.TextField(blank=True, default='this too'),
        ),
    ]
