# Generated by Django 2.1.5 on 2019-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20190129_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_detail',
            name='author_bio',
        ),
        migrations.AddField(
            model_name='author',
            name='author_bio',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
