# Generated by Django 2.1.5 on 2019-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20190129_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_portfolio',
            field=models.URLField(blank=True, default='if have one :p', max_length=50),
        ),
    ]
