# Generated by Django 2.1.5 on 2019-01-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_author_author_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_detail',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='author_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Author_Detail',
        ),
    ]
