# Generated by Django 2.1.5 on 2019-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20190129_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_linkedin',
            field=models.URLField(blank=True),
        ),
    ]
