# Generated by Django 2.1.5 on 2019-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20190129_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('TECHNICAL', 'tech'), ('PROGRAMMING', 'programming'), ('LIFE', 'life')], default=True, max_length=30),
            preserve_default=False,
        ),
    ]
