# Generated by Django 2.1.5 on 2019-01-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_post_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_about_title', models.CharField(max_length=50)),
                ('owner_about_message', models.TextField()),
                ('owner_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Owner')),
            ],
        ),
    ]
