# Generated by Django 2.1.5 on 2019-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_ownerabout_owner_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=30)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_subject', models.CharField(max_length=30)),
                ('your_message', models.TextField()),
            ],
        ),
    ]
