# Generated by Django 2.1.5 on 2019-01-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='person_email',
        ),
    ]
