# Generated by Django 2.1.5 on 2019-01-31 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_remove_comment_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eye_Catcher_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_message_first_para', models.CharField(max_length=100)),
                ('post_image_first_para', models.ImageField(blank=True, null=True, upload_to='PostImg')),
                ('post_message_second_para', models.CharField(blank=True, max_length=100, null=True)),
                ('post_image_second_para', models.ImageField(blank=True, null=True, upload_to='PostImg')),
                ('post_message_third_para', models.CharField(blank=True, max_length=100, null=True)),
                ('post_image_third_para', models.ImageField(blank=True, null=True, upload_to='PostImg')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Author')),
            ],
        ),
    ]
