# Generated by Django 2.1.5 on 2019-01-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_eye_catcher_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eye_catcher_post',
            name='post_image_first_para',
        ),
        migrations.AddField(
            model_name='eye_catcher_post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='PostImg'),
        ),
    ]
