# Generated by Django 2.1.5 on 2019-01-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_auto_20190131_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='eye_catcher_post',
            name='post_category',
            field=models.CharField(choices=[('TECHNICAL', 'technical'), ('LIFE', 'life'), ('PROGRAMMING', 'programming')], default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eye_catcher_post',
            name='post_tages',
            field=models.CharField(choices=[('PYTHON', 'python'), ('DJANGO', 'django'), ('ANDROID', 'android')], default=True, max_length=30),
            preserve_default=False,
        ),
    ]
