# Generated by Django 2.1.5 on 2019-01-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_popular_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Popular_Posts',
            new_name='Popular_Post',
        ),
    ]
