# Generated by Django 2.1.5 on 2019-02-01 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0026_auto_20190131_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='eye_catcher_post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
